apiVersion: v1
kind: Pod
metadata:
  name: 10.0.10.142-rockygui
spec:
  containers:
  - name: rocky
    image: minkoong/rockylinuxg
    command: ["/sbin/init"]
  nodeSelector:
    disktype: 10.0.10.142
